version: "3.9"

services:
  php-apache:
    image: thecodingmachine/php:8.3-v5-apache-node20

    volumes:
      - /var/lib/docker/volumes/arcane_arcane-data/_data/projects/Microweber_-_Dieter:/var/www/html

    depends_on:
      - mariadb

    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
      APACHE_EXTENSION_DAV: 0
      PHP_INI_MEMORY_LIMIT: 1g
      PHP_INI_ERROR_REPORTING: E_ALL
      PHP_EXTENSIONS: pgsql gettext imap sockets zip curl dom gd exif intl mbstring bcmath opcache soap xml xmlrpc fileinfo pdo_sqlite pdo_mysql pdo_pgsql
      PECL_EXTENSION: sodium
      STARTUP_COMMAND_1: composer install

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      - "traefik.http.routers.micro.rule=Host(`micro.dietergijsen.be`)"
      - "traefik.http.routers.micro.entrypoints=web"
      - "traefik.http.routers.micro.middlewares=redirect-to-https"

      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

      - "traefik.http.routers.micro-secure.rule=Host(`micro.dietergijsen.be`)"
      - "traefik.http.routers.micro-secure.entrypoints=websecure"
      - "traefik.http.routers.micro-secure.tls=true"
      - "traefik.http.routers.micro-secure.tls.certresolver=letsencrypt"

      - "traefik.http.services.micro.loadbalancer.server.port=80"

    networks:
      - proxy

  mariadb:
    image: mariadb:10.3

    volumes:
      - mariadb:/var/lib/mysql

    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "laravel"
      MYSQL_PASSWORD: "laravel"
      MYSQL_DATABASE: "laravel"

    networks:
      - proxy

volumes:
  mariadb:

networks:
  proxy:
    external: true
